#!/usr/bin/env zsh

if [[ "${SSH_TTY}" != "" ]]; then
    export PINENTRY_USER_DATA="ssh"
fi;

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="aussiegeek"
zstyle ':omz:update' mode auto
plugins=(git man lxd kubectl zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh

autoload -U compinit && compinit -D 2>&1 >/dev/null
autoload -U compaudit && compaudit 2>&1 >/dev/null
autoload -U promptinit && promptinit 2>&1 >/dev/null
autoload -U colors && colors 2>&1 >/dev/null

setopt no_automenu
setopt bashautolist
setopt interactive_comments
setopt histignorespace

if [[ -e "${HOME}/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
    source "${HOME}/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi
if [[ -e "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then 
    source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
fi

export XDG_DATA_DIRS="${HOME}/.nix-profile/share/:${XDG_DATA_DIRS}"

export SHELL="$(which zsh)"
export EDITOR="$(which vim)"

export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

export PATH="${PATH}:${HOME}/.bin"
export PATH="${PATH}:${HOME}/.dotnet/tools"

alias open="xdg-open &> /dev/null"
alias ip6="ip -c -6"
alias ip="ip -c"
alias watch="watch --color"
alias date3339="date --rfc-3339=date"
alias mann="BROWSER=firefox man --html"
alias code="code --new-window"
alias ffmpreg="ffmpeg"
alias ffprobe="ffprobe -hide_banner"
alias dog="dig"

##                                                                            Don't attach to a tmux session if in vscode context
if [ -x "$(command -v tmux)" ] && [ -n "${DISPLAY}" ] && [ -z "${TMUX}" ] && [ -z "${VSCODE_INJECTION}" ]; then
    tmux attach \; choose-tree -s || tmux >/dev/null 2>&1
fi
